In [1]:
import torch

In [2]:
t1=torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2=torch.tensor([[5.,6],
                [7,8],
                [9,10]])
t2

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t2.shape

torch.Size([3, 2])

Tensor and Gradient desent Creations 

In [7]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [8]:
#  compute the linear Ligression

y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [9]:
# COMPUTE THR derivative

y.backward()

In [10]:
print('dy/dx',x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [11]:
# compute the a tensor a fixed for every element
t6=torch.full((89,8),47)
t6
#  full((row,colom),value)

tensor([[47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 47, 47],
        [47, 47, 47, 47, 47, 47, 4

NUMPY<PANDAS, Matplotlib OpenCv

In [12]:
import numpy as np


In [13]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [14]:
y=torch.from_numpy(x)
y

tensor([1, 2, 3, 4], dtype=torch.int32)

In [15]:
y.dtype


torch.int32

In [16]:
z=y.numpy()
z

array([1, 2, 3, 4])

                                                0 to Linear Regression && Gradient Desent
                                                


In [17]:
# inpute (tem,rain,hunimidty)
inputs=np.array([[73.,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')
inputs
                

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [18]:
# input the tergets (apple,orrange)
tergets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')
tergets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [19]:
# convert the numpyt to torch
inputs=torch.from_numpy(inputs)
tergets=torch.from_numpy(tergets)
print(inputs)
print(tergets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


To Create Linear Ligressinon Model

In [20]:
# wight and bais
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.5800,  0.0273,  1.2722],
        [-0.0032, -0.3089,  2.1176]], requires_grad=True)
tensor([-2.6553,  0.9675], requires_grad=True)


In [21]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [22]:
inputs@ w.t()+b

tensor([[ -61.4649,   71.0936],
        [ -62.6167,  109.0182],
        [ -62.6753,   82.1171],
        [-115.5722,   65.7083],
        [ -20.0056,  119.3232]], grad_fn=<AddBackward0>)

In [23]:
# Define the model
def model (x):
    return x@ w.t()+b

In [24]:
pred=model(inputs)
print(pred)

tensor([[ -61.4649,   71.0936],
        [ -62.6167,  109.0182],
        [ -62.6753,   82.1171],
        [-115.5722,   65.7083],
        [ -20.0056,  119.3232]], grad_fn=<AddBackward0>)


In [25]:
# print the tergets
print(tergets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [26]:
diff=pred-tergets
torch.sum(diff*diff)/diff.numel()

tensor(10496.4971, grad_fn=<DivBackward0>)

Loss Funtion
1. Calculate the differetn between predict and tergets
2. Squer Every elemet and remove the nagative form
3. calculte the avarege of the element in the resulting matrix

In [27]:
# MSE
def mse(t1,t2):
    diff=t1-t2
    
    return torch.sum(diff*diff)/diff.numel()
        

In [28]:
loss=mse(pred,tergets)
print(loss)

tensor(10496.4971, grad_fn=<DivBackward0>)


Now Compute the gradient desent 

1.with pyTorch ,we can automatically comput the becouse from the  requires_grad=True value
2.

In [29]:
loss.backward()

In [30]:
print(w)
print(w.grad)

tensor([[-1.5800,  0.0273,  1.2722],
        [-0.0032, -0.3089,  2.1176]], requires_grad=True)
tensor([[-11993.9102, -12515.4102,  -7696.0376],
        [  -133.3546,   -954.7895,   -261.2372]])


In [31]:
print(w)
w.grad

tensor([[-1.5800,  0.0273,  1.2722],
        [-0.0032, -0.3089,  2.1176]], requires_grad=True)


tensor([[-11993.9102, -12515.4102,  -7696.0376],
        [  -133.3546,   -954.7895,   -261.2372]])

In [32]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5

In [33]:
w,b

(tensor([[-1.4601e+00,  1.5242e-01,  1.3491e+00],
         [-1.8752e-03, -2.9933e-01,  2.1202e+00]], requires_grad=True),
 tensor([-2.6539,  0.9675], requires_grad=True))

In [34]:
# now verify the loss is actually lower
pred=model(inputs)

loss=mse(pred,tergets)
print(loss)

tensor(7211.8296, grad_fn=<DivBackward0>)


In [35]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


Train the model using gradient desecent

1. Generate the predictions
2. claculte the loss
3. compute the gradient w.r.t W and B
4. Adjust the W by substracting a small quantity proportional to the gradient
5. Reset the Gredient to Zero

In [36]:
# Step 1
#  generate prediction
pred=model(inputs)
print(pred)

tensor([[-41.0133,  71.9430],
        [-35.7618, 110.1470],
        [-31.0049,  83.6641],
        [-95.1078,  66.3516],
        [  5.6736, 120.5147]], grad_fn=<AddBackward0>)


In [37]:
# step 2
# compute the loss fucntion
loss=mse(pred,tergets)
print(loss)

tensor(7211.8296, grad_fn=<DivBackward0>)


In [38]:
# Step 3
# compute the gradient desecent
loss.backward()
print(w.grad)
print(b.grad)


tensor([[ -9883.6465, -10250.9092,  -6298.0889],
        [   -43.9266,   -853.6731,   -200.0978]])
tensor([-115.6428,   -1.4759])


In [39]:
# Step 3
# Adjust the Wight and biases
with torch.no_grad():

    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [40]:
print(w)
print(b)

tensor([[-1.3612e+00,  2.5493e-01,  1.4121e+00],
        [-1.4359e-03, -2.9080e-01,  2.1222e+00]], requires_grad=True)
tensor([-2.6528,  0.9676], requires_grad=True)


In [41]:
# calculete the loss
pred=model(inputs)
loss=mse(pred,tergets)
print(loss)

tensor(4997.1138, grad_fn=<DivBackward0>)


Train for Muliple epochs

In [42]:
# train for 100 epochs

for i in range(50):
    pred=model(inputs)
    loss=mse(pred,tergets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad * 1e-5
        b-=b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
    

In [43]:
# calculete the losss
pred=model(inputs)
loss=mse(pred,tergets)
print(loss)

tensor(283.7984, grad_fn=<DivBackward0>)


In [44]:
pred

tensor([[ 53.5597,  74.2218],
        [ 87.6347, 113.6230],
        [112.1121,  97.2112],
        [  3.5120,  59.8570],
        [121.0955, 128.5326]], grad_fn=<AddBackward0>)

In [45]:
tergets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Linear Regrassion Uing built funciton in PyTorch

In [46]:
import torch.nn as nn

In [47]:
# inpute (tem,rain,hunimidty)
inputs=np.array([[73.,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')

# input the tergets (apple,orrange)
tergets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')
inputs=torch.from_numpy(inputs)
tergets=torch.from_numpy(tergets)



In [48]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [49]:
tergets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [50]:
from torch.utils.data import TensorDataset

In [51]:
# define the dataset

train_ds=TensorDataset(inputs,tergets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [52]:
from torch.utils.data import DataLoader

In [53]:
# define the data loader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [54]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]])
tensor([[103., 119.],
        [119., 133.],
        [ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.]])


NN. linear

In [58]:
# defien the model

model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0058, -0.3227, -0.2524],
        [-0.2465, -0.5691, -0.1952]], requires_grad=True)
Parameter containing:
tensor([0.2604, 0.4660], requires_grad=True)


In [61]:
# Perametter

list(model.parameters())

[Parameter containing:
 tensor([[-0.0058, -0.3227, -0.2524],
         [-0.2465, -0.5691, -0.1952]], requires_grad=True),
 Parameter containing:
 tensor([0.2604, 0.4660], requires_grad=True)]

In [62]:
# now compute the predict
pred=model(inputs)
pred

tensor([[ -32.6359,  -64.0537],
        [ -44.8168,  -84.5415],
        [ -58.1239, -108.5618],
        [ -23.5447,  -56.3743],
        [ -48.7852,  -84.8414]], grad_fn=<AddmmBackward0>)

In [64]:
# compute the loss fucniton
# first input the nn.funciton
import torch.nn.functional as p

In [65]:
# define the loss model
loss_fs=p.mse_loss

In [66]:
loss=loss_fs(model(inputs),tergets)
print(loss)

tensor(24119.0293, grad_fn=<MseLossBackward0>)


In [68]:
# ptimizer the loss
# Gredient desecent
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

Train the Model



1.Generate the prediction.

2.calcultete the loss fucntion

3.compute the gradient desecent

4.Adjust the wieght and by substrating as small quility proporstional to the gradient desent

5.reset the gradeint to zero

In [69]:
# utility function to train the model

def fit(num_epochs,model,loss_fs,opt,train_dl):
    for epoch in range(num_epochs):
        # train with batch of data
        for xb,xy in train_dl:
            # generate the prediction
            pred=model(xb)
            # 2.calcultet the loss
            loss=loss_fs(pred,yb)
            # 3. compute the gradient 
            loss.backward()
            # 4. updatet hee peremeters
            opt.step()
            # 5. reset the gradient to zero
            opt.zero_grad()
        # print the progress
        if(epoch+1)%10==0:
            print('Epoch [{}/{}],loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))



In [71]:
fit(100,model,loss_fs,opt,train_dl)

Epoch [10/100],loss: 1694.5164
Epoch [20/100],loss: 1600.8057
Epoch [30/100],loss: 1145.3015
Epoch [40/100],loss: 862.5938
Epoch [50/100],loss: 835.8906
Epoch [60/100],loss: 1242.4111
Epoch [70/100],loss: 846.7591
Epoch [80/100],loss: 1520.4089
Epoch [90/100],loss: 843.4614
Epoch [100/100],loss: 1521.8557


In [72]:
# generate the pred
pred=model(inputs)
pred

tensor([[ 63.1325,  75.8005],
        [ 80.9041,  98.8048],
        [ 85.2411, 101.4493],
        [ 76.2559,  89.2773],
        [ 69.4516,  87.4386]], grad_fn=<AddmmBackward0>)

In [73]:
# compute the terget
tergets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [76]:
model(torch.tensor([[75,63,44.]]))

tensor([[63.8518, 76.8526]], grad_fn=<AddmmBackward0>)